services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: momo_demo
    ports:
      - "5432:5432"
    volumes:
      - dbdata_momo:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  db2:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pula_pay_db
    ports:
      - "5433:5432"
    volumes:
      - dbdata_pulapay:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  back:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/momo_demo?schema=public

  front:
    build: ./front
    ports:
      - "8080:80"
    depends_on:
      - back

volumes:
  dbdata_momo:
  dbdata_pulapay: